routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Route::middleware(['auth','admins'])->group(function()
//{
Route::resource('candidates', 'CandidateController');
Route::resource('voters', 'VoterController');
Route::resource('parties', 'PartyController');
//});
Route::get('votings/voter_login','VotingPannelController@voter_login')->name('votings.voter_login');
Route::get('votings/index','VotingPannelController@index')->name('votings.index');
Route::get('votings/voter_auth','VotingPannelController@voter_auth')->name('votings.voter_auth');
Route::get('votings/final','VotingPannelController@final')->name('votings.final');
Route::get('votings/vote_save','VotingPannelController@vote_save')->name('votings.vote_save');

app/Candidate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Candidate extends Model
{
    public function party()
    {
        return $this->belongsTo('App\Party');
    }
    public function voters()
    {
        return $this->belongsToMany('App\Voter');
    }
}

app/Http/Controllers/CandidateController.php
<?php

namespace App\Http\Controllers;

use App\Candidate;
use App\Party;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;

class CandidateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $candidates=Candidate::all();
        return view('Candidate.index')->withCandidates($candidates);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $parties=Party::all();
        return view('Candidate.create')->withParties($parties);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $candidate=new Candidate;
        $candidate->name=$request->name;
        $candidate->state=$request->state;
        $candidate->district=$request->district;
        $candidate->party_id=$request->party_id;
        $candidate->save();
        
        return redirect()->route('candidates.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Candidate  $candidate
     * @return \Illuminate\Http\Response
     */
    public function show(Candidate $candidate)
    {
        return view('Candidate.show')->withCandidate($candidate);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Candidate  $candidate
     * @return \Illuminate\Http\Response
     */
    public function edit(Candidate $candidate)
    {
        return view('Candidate.edit')->withCandidate($candidate);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Candidate  $candidate
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Candidate $candidate)
    {
        $candidate->name=$request->name;
        $candidate->state=$request->state;
        $candidate->district=$request->district;
        $candidate->party=$request->party;

        $candidate->save();
        return redirect()->route('candidates.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Candidate  $candidate
     * @return \Illuminate\Http\Response
     */
    public function destroy(Candidate $candidate)
    {
        $candidate->delete();
        return redirect()->route('candidates.index');
    }
}

resources/views/Candidate/create.blade.php
@extends('layouts.masterlayout')
@section('content')


<form method="POST" action="{{route('candidates.store')}}" > 
    @csrf()
    <h1>Create Candidate:</h1>
   
   
    <div class="form-group">
    <label >Candidate Name</label>
    <input type="text" class="form-control" name="name"  placeholder="Enter name">
    <small  class="form-text text-danger"></small>
</div><br>

<div class="form-group">
    <label >Candidate State:</label>
    <input type="text" class="form-control" name="state"  placeholder="Enter name">
    <small  class="form-text text-danger"></small>
</div><br>

<div class="form-group">
    <label >Candidate District:</label>
    <input type="text" class="form-control" name="district"  placeholder="Enter name">
    <small  class="form-text text-danger"></small>
</div><br>

<div class="form-group">
    <label >Candidate Party:</label>
    <select class="js-example-basic-multiple" name="party_id" style="width:100%">
  <option disabled>select Party</option>
  @foreach($parties as $party)
  <option value="{{ $party->id }}">{{ $party->name }}</option>
        @endforeach
</select>
</div><br>

<div>

  <button type="submit" class="btn btn-primary">Submit</button>
  </div>
</form>
@endsection

resources/views/Candidate/edit.blade.php
@extends('layouts.masterlayout')
@section('content')


<form method="POST" action="{{route('candidates.update',$candidate)}}" > 
    @csrf()
    @method('PUT')
    <h1>Edit Candidate:</h1>
   
   
    <div class="form-group">
    <label >Candidate Name</label>
    <input type="text" class="form-control" name="name" value="{{$candidate->name}}" placeholder="Enter name">
    <small  class="form-text text-danger"></small>
</div><br>


<div class="form-group">
    <label >Candidate State:</label>
    <input type="text" class="form-control" name="state" value="{{$candidate->state}}" placeholder="Enter name">
    <small  class="form-text text-danger"></small>
</div><br>

<div class="form-group">
    <label >Candidate District:</label>
    <input type="text" class="form-control" name="district" value="{{$candidate->district}}" placeholder="Enter name">
    <small  class="form-text text-danger"></small>
</div><br>

<div class="form-group">
    <label >Candidate Party:</label>
    <input type="text" class="form-control" name="party" value="{{$candidate->party}}" placeholder="Enter name">
    <small  class="form-text text-danger"></small>
</div><br>

<div>

  <button type="submit" class="btn btn-primary">Submit</button>
  </div>

</form>
@endsection

resources/views/Candidate/index.blade.php
@extends('layouts.masterlayout')
@section('content')

   
    <a href="{{route('candidates.create')}}" class="btn btn-info" style="margin-left:700px">Add new Candidate</a>

    <table class="table table-dark" style="margin-top:50px">

    <tr>
      <th>Candidate ID</th>
      <th>Candidate Name</th>
      <th>State</th>
      <th>District</th>
      <th>Party</th>
      <th>Action</th>
    
    </tr>

@foreach($candidates as $candidate)
<tr>
    <td>{{$candidate->id}}</td>
    <td>
    {{$candidate->name}}
    </td>
    <td>
    {{$candidate->state}}
    </td>
    <td>
    {{$candidate->district}}
    </td>
    <td>
    {{$candidate->party->name}}
    </td>
    <td class="form-group row" >
    
    <a href="{{route('candidates.show',$candidate)}}" ><i class="fas fa-eye" style="margin-left:50px;color:#00BFFF"></i></button></a>
  
    <a href="{{route('candidates.edit',$candidate)}}" ><i class="fas fa-edit" style="margin-left:50px;color:#00BFFF"></i></button></a>
 
    
   
    <form action="{{route('candidates.destroy',$candidate)}}" method="POST">
    @csrf()
    @method('delete')
    <button style="margin-left:40px;color:#00BFFF; background-color:transparent; border:none" class="fas fa-trash"></button></td>
    </form>

    </tr>
    @endforeach

  </table>
@endsection

resources/views/Candidate/show.blade.php
@extends('layouts.masterlayout')
@section('content')


    <table class="table table-dark" style="margin-top:50px">

    <tr>
      <th>Candidate ID</th>
      <th>Candidate Name</th>
      <th>State</th>
      <th>District</th>
      <th>Party</th>
      <th>Action</th>
    
    </tr>
<tr>
    <td>{{$candidate->candidate_id}}</td>
    <td>
    {{$candidate->name}}
    </td>
    <td>
    {{$candidate->state}}
    </td>
    <td>
    {{$candidate->District}}
    </td>
    <td>
    {{$candidate->party}}
    </td>
    

    </tr>

  </table>
    
@endsection