routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Route::middleware(['auth','admins'])->group(function()
//{
Route::resource('candidates', 'CandidateController');
Route::resource('voters', 'VoterController');
Route::resource('parties', 'PartyController');
//});
Route::get('votings/voter_login','VotingPannelController@voter_login')->name('votings.voter_login');
Route::get('votings/index','VotingPannelController@index')->name('votings.index');
Route::get('votings/voter_auth','VotingPannelController@voter_auth')->name('votings.voter_auth');
Route::get('votings/final','VotingPannelController@final')->name('votings.final');
Route::get('votings/vote_save','VotingPannelController@vote_save')->name('votings.vote_save');

app/Voter.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Voter extends Model
{
    public function candidates()
    {
        return $this->belongsTo('App\Candidate');
    }
}

app/Http/Controllers/VoterController.php
<?php

namespace App\Http\Controllers;

use App\Voter;
use Illuminate\Http\Request;

class VoterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $voters=Voter::all();
        return view('Voter.index')->withVoters($voters);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Voter.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $voter=new Voter;
        $voter->name=$request->name;
        $voter->adhar_no=$request->adhar_no;
        $voter->dob=$request->dob;
        $voter->state=$request->state;
        $voter->district=$request->district;
        $voter->save();
        return redirect()->route('voters.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Voter  $voter
     * @return \Illuminate\Http\Response
     */
    public function show(Voter $voter)
    {
        return view('Voter.show')->withVoter($voter);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Voter  $voter
     * @return \Illuminate\Http\Response
     */
    public function edit(Voter $voter)
    {
        return view('Voter.edit')->withVoter($voter);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Voter  $voter
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Voter $voter)
    {
        $voter->name=$request->name;
        $voter->state=$request->state;
        $voter->district=$request->district;
        $voter->adhar_no=$request->adhar_no;
        $voter->dob=$request->dob;

        $voter->save();
        return redirect()->route('voters.index');
    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Voter  $voter
     * @return \Illuminate\Http\Response
     */
    public function destroy(Voter $voter)
    {
        $voter->delete();
        return redirect()->route('voters.index');
    }
}

resources/views/Voter/create.blade.php
@extends('layouts.masterlayout')
@section('content')



<form method="POST" action="{{route('voters.store')}}" > 
    @csrf()
    <h1>Create Voter:</h1>
   
   
    <div class="form-group">
    <label >Voter Name</label>
    <input type="text" class="form-control" name="name"  placeholder="Enter name">
    <small  class="form-text text-danger"></small>
</div><br>
<div class="form-group">
    <label >Adhar no</label>
    <input type="text" class="form-control" name="adhar_no"  placeholder="Enter name">
    <small  class="form-text text-danger"></small>
</div><br>
<div class="form-group">
    <label >Date of birth</label>
    <input type="text" class="form-control" name="dob"  placeholder="Enter name">
    <small  class="form-text text-danger"></small>
</div><br>

<div class="form-group">
    <label >Voter State:</label>
    <input type="text" class="form-control" name="state"  placeholder="Enter name">
    <small  class="form-text text-danger"></small>
</div><br>

<div class="form-group">
    <label >Voter District:</label>
    <input type="text" class="form-control" name="district"  placeholder="Enter name">
    <small  class="form-text text-danger"></small>
</div><br>
<div class="form-group">
    <label >Voting Status:</label>
    <input disabled type="text" class="form-control" name="status" value="0" placeholder="Enter name">
    <small  class="form-text text-danger"></small>
</div><br>


  <button type="submit" class="btn btn-primary">Submit</button>
  </div>

@endsection

resources/views/Voter/edit.blade.php
@extends('layouts.masterlayout')
@section('content')


<form method="POST" action="{{route('voters.update',$voter)}}" > 
    @csrf()
    @method('PUT')
    <h1>Update Voter:</h1>
   
   
    <div class="form-group">
    <label >Voter Name</label>
    <input type="text" class="form-control" name="name" value="{{$voter->name}}" placeholder="Enter name">
    <small  class="form-text text-danger"></small>
</div><br>

<div class="form-group">
    <label >Voter State:</label>
    <input type="text" class="form-control" name="state" value="{{$voter->state}}" placeholder="Enter name">
    <small  class="form-text text-danger"></small>
</div><br>

<div class="form-group">
    <label >Voter District:</label>
    <input type="text" class="form-control" name="district" value="{{$voter->district}}" placeholder="Enter name">
    <small  class="form-text text-danger"></small>
</div><br>


  <button type="submit" class="btn btn-primary">Submit</button>
  </div>

@endsection

resources/views/Voter/index.blade.php
@extends('layouts.masterlayout')
@section('content')
 
<h1>All Voters</h1>
   
    <a href="{{route('voters.create')}}" class="btn btn-info" style="margin-left:700px">Add new Voter</a>

    <table class="table table-dark" style="margin-top:50px">

    <tr>
      <th>Voter ID</th>
      <th>Voter Name</th>
      <th>State</th>
      <th>District</th>
      <th>Action</th>
    
    </tr>

@foreach($voters as $voter)
<tr>
    <td>{{$voter->id}}</td>
    <td>
    {{$voter->name}}
    </td>
    <td>
    {{$voter->state}}
    </td>
    <td>
    {{$voter->district}}
    </td>

    <td class="form-group row" >
    
    <a href="{{route('voters.show',$voter)}}" ><i class="fas fa-eye" style="margin-left:50px;color:#00BFFF"></i></button></a>
  
    <a href="{{route('voters.edit',$voter)}}" ><i class="fas fa-edit" style="margin-left:50px;color:#00BFFF"></i></button></a>
 
    
   
    <form action="{{route('voters.destroy',$voter)}}" method="POST">
    @csrf()
    @method('delete')
    <button style="margin-left:40px;color:#00BFFF; background-color:transparent; border:none" class="fas fa-trash"></button></td>
    </form>

    </tr>
    @endforeach

  </table>
@endsection

resources/views/Voter/show.blade.php
@extends('layouts.masterlayout')
@section('content')   
<h1>All Voters</h1>
   
    <a href="{{route('voters.create')}}" class="btn btn-info" style="margin-left:700px">Add new Voter</a>

    <table class="table table-dark" style="margin-top:50px">

    <tr>
      <th>Voter ID</th>
      <th>Voter Name</th>
      <th>State</th>
      <th>District</th>
    
    </tr>


<tr>
    <td>{{$voter->id}}</td>
    <td>
    {{$voter->name}}
    </td>
    <td>
    {{$voter->state}}
    </td>
    <td>
    {{$voter->district}}
    </td>

    </tr>
  

  </table>
@endsection